# Generated by Django 2.1.7 on 2019-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32, null=True, unique=True)),
                ('token', models.CharField(max_length=32, null=True, unique=True)),
                ('last_login_time', models.DateTimeField()),
                ('register_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_t',
            },
        ),
    ]
